name: Validate & Test

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
      - name: Validate
        run: |
          pnpm check
          pnpm lint:ci

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
      - name: Test
        run: pnpm test run --coverage
