name: Validate & Test

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: lts/Krypton
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Validate
        run: |
          pnpm check
          pnpm lint:ci

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: lts/Krypton
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Test
        run: pnpm test run --coverage
